steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress-docker-image:latest', '.']

images:
- 'gcr.io/$PROJECT_ID/wordpress-docker-image:latest'

options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s